apiVersion: v1
kind: Service
metadata:
  labels:
    tier: statistics-service
  name: statistics-service
spec:
  selector:
    tier: statistics-service
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: statistics-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: statistics-service
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service
  labels:
    tier: statistics-service
    app: microservices
  annotations:
    "sidecar.jaegertracing.io/inject": simplest
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: statistics-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: statistics-service
    spec:
      containers:
        - name: statistics-service
          image: darktw1nk/statistics-service:1.1.0
          livenessProbe:
              httpGet:
                path: /health/live
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 3
          readinessProbe:
              httpGet:
                path: /health/ready
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 3
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "4Gi"
              cpu: "2000m"
            requests:
              memory: "256Mi"
              cpu: "50m"
