apiVersion: v1
kind: Service
metadata:
  labels:
    tier: user-2
  name: user-2
spec:
  selector:
    tier: user-2
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  type: NodePort

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-2
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-2
  labels:
    tier: user-2
    app: microservices
  annotations:
    "sidecar.jaegertracing.io/inject": simplest
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: user-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: user-2
    spec:
      containers:
        - name: user-2
          image: darktw1nk/user-2-service:1.2.1
          livenessProbe:
              httpGet:
                path: /health/live
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 3
          readinessProbe:
              httpGet:
                path: /health/ready
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 3
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "4Gi"
              cpu: "2000m"
            requests:
              memory: "256Mi"
              cpu: "50m"
